name: Verify Release Bundle
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
  release:
    types: [published]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install tooling
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Download assets
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          tag="${{ github.event.release.tag_name || github.event.inputs.tag }}"
          mkdir -p work && cd work
          gh release download "$tag"
          sha256sum -c p39_release_checksums.txt
          tar -tzf p39_release_*.tgz | egrep 'manifest_(equity_fixed100k|proxy)\.json|scoreboard_(equity_fixed100k|proxy)\.csv|risk_limits\.json|_test_trades\.csv|_trials_metrics\.csv' >/dev/null
